import { ThemePreset } from "./types";
import bananaBg1 from "../../../assets/social-share/nano_banana_fitness_bg_1.png";
import bananaBg2 from "../../../assets/social-share/nano_banana_fitness_bg_2.png";
import bananaBg3 from "../../../assets/social-share/nano_banana_fitness_bg_3.png";
import fitnessBg1 from "../../../assets/social-share/fitness-gym.png";
import fitnessBg2 from "../../../assets/social-share/fitness-mat.png";
import fitnessBg3 from "../../../assets/social-share/fitness-weights.png";

export const THEMES: Record<string, ThemePreset> = {
  dark: {
    backgroundColor: "#121212",
    primaryTextColor: "#fff",
    secondaryTextColor: "#71717a",
    accentColor: "#3b82f6",
    preview: "linear-gradient(135deg,#121212,#1e293b)",
    label: "Dark",
  },
  sunset: {
    backgroundColor: "#2b0a0f",
    primaryTextColor: "#fff7ed",
    secondaryTextColor: "#fdba74",
    accentColor: "#fb7185",
    preview: "linear-gradient(135deg,#2b0a0f,#4c1d2d)",
    label: "Sunset",
  },
  violet: {
    backgroundColor: "#1a0a2e",
    primaryTextColor: "#faf5ff",
    secondaryTextColor: "#c4b5fd",
    accentColor: "#a78bfa",
    preview: "linear-gradient(135deg,#1a0a2e,#3b1f6e)",
    label: "Violet",
  },
  soft: {
    backgroundColor: "#f8fafc",
    primaryTextColor: "#0f172a",
    secondaryTextColor: "#64748b",
    accentColor: "#6366f1",
    isLight: true,
    preview: "linear-gradient(135deg,#f8fafc,#e2e8f0)",
    label: "Soft",
  },
  fitness1: {
    backgroundColor: "#111827",
    primaryTextColor: "#ffffff",
    secondaryTextColor: "#9ca3af",
    accentColor: "#3b82f6",
    backgroundImage: fitnessBg1,
    preview: `url(${fitnessBg1})`,
    label: "Professional Gym",
  },
  fitness2: {
    backgroundColor: "#2d3748",
    primaryTextColor: "#f7fafc",
    secondaryTextColor: "#a0aec0",
    accentColor: "#48bb78",
    backgroundImage: fitnessBg2,
    preview: `url(${fitnessBg2})`,
    label: "Zen Studio",
  },
  fitness3: {
    backgroundColor: "#1a202c",
    primaryTextColor: "#ffffff",
    secondaryTextColor: "#718096",
    accentColor: "#e53e3e",
    backgroundImage: fitnessBg3,
    preview: `url(${fitnessBg3})`,
    label: "Power Weights",
  },
  banana1: {
    backgroundColor: "#1a1a1a",
    primaryTextColor: "#ffffff",
    secondaryTextColor: "#fbbf24",
    accentColor: "#f59e0b",
    backgroundImage: bananaBg1,
    preview: `url(${bananaBg1})`,
    label: "Nano Fitness",
  },
  banana2: {
    backgroundColor: "#000000",
    primaryTextColor: "#fef3c7",
    secondaryTextColor: "#fcd34d",
    accentColor: "#fbbf24",
    backgroundImage: bananaBg2,
    preview: `url(${bananaBg2})`,
    label: "Nano Abstract",
  },
  banana3: {
    backgroundColor: "#fffbeb",
    primaryTextColor: "#78350f",
    secondaryTextColor: "#92400e",
    accentColor: "#d97706",
    isLight: true,
    backgroundImage: bananaBg3,
    preview: `url(${bananaBg3})`,
    label: "Nano Cute",
  },
};

export const STICKERS = [
  "🔥",
  "💪",
  "⚡",
  "🏆",
  "🚀",
  "😤",
  "🎯",
  "👊",
  "🫡",
  "✨",
  "🦍",
  "🏋️‍♂️",
  "💦",
  "📈",
  "👑",
  "🔋",
  "🦾",
  "🤯",
  "🥵",
  "✅",
  "🎉",
  "🤝",
  "💯",
  "😎",
  "💪🏽",
  "🍎",
  "🥩",
  "🥞",
  "💊",
];
