import { ThemePreset } from "./types";

export const THEMES: Record<string, ThemePreset> = {
  dark: {
    backgroundColor: "#121212",
    primaryTextColor: "#fff",
    secondaryTextColor: "#71717a",
    accentColor: "#3b82f6",
    preview: "linear-gradient(135deg,#121212,#1e293b)",
    label: "Dark",
  },
  cobalt: {
    backgroundColor: "#0a1023",
    primaryTextColor: "#f8fafc",
    secondaryTextColor: "#93c5fd",
    accentColor: "#38bdf8",
    preview: "linear-gradient(135deg,#0a1023,#1e3a5f)",
    label: "Cobalt",
  },
  sunset: {
    backgroundColor: "#2b0a0f",
    primaryTextColor: "#fff7ed",
    secondaryTextColor: "#fdba74",
    accentColor: "#fb7185",
    preview: "linear-gradient(135deg,#2b0a0f,#4c1d2d)",
    label: "Sunset",
  },
  emerald: {
    backgroundColor: "#0a1f1a",
    primaryTextColor: "#ecfdf5",
    secondaryTextColor: "#6ee7b7",
    accentColor: "#34d399",
    preview: "linear-gradient(135deg,#0a1f1a,#064e3b)",
    label: "Emerald",
  },
  violet: {
    backgroundColor: "#1a0a2e",
    primaryTextColor: "#faf5ff",
    secondaryTextColor: "#c4b5fd",
    accentColor: "#a78bfa",
    preview: "linear-gradient(135deg,#1a0a2e,#3b1f6e)",
    label: "Violet",
  },
  snow: {
    backgroundColor: "#ffffff",
    primaryTextColor: "#1e293b",
    secondaryTextColor: "#64748b",
    accentColor: "#3b82f6",
    isLight: true,
    preview: "linear-gradient(135deg,#ffffff,#f1f5f9)",
    label: "Snow",
  },
  soft: {
    backgroundColor: "#f8fafc",
    primaryTextColor: "#0f172a",
    secondaryTextColor: "#64748b",
    accentColor: "#6366f1",
    isLight: true,
    preview: "linear-gradient(135deg,#f8fafc,#e2e8f0)",
    label: "Soft",
  },
};

export const STICKERS = [
  "🔥",
  "💪",
  "⚡",
  "🏆",
  "🚀",
  "😤",
  "🎯",
  "👊",
  "🫡",
  "✨",
  "🦍",
  "🏋️‍♂️",
  "💦",
  "📈",
  "👑",
  "🔋",
  "🦾",
  "🤯",
  "🥵",
  "✅",
  "🎉",
  "🤝",
  "💯",
  "😎",
  "💪🏽",
  "🍎",
  "🥩",
  "🥞",
  "💊",
];
