import { z } from "zod";

const ModeSchema = z.preprocess(
  (value) => {
    if (typeof value !== "string") return value;
    const normalized = value.trim().toLowerCase();
    if (
      normalized.includes("heavy") ||
      normalized.includes("fuerza") ||
      normalized.includes("strength")
    ) {
      return "heavy";
    }
    if (
      normalized.includes("light") ||
      normalized.includes("liger") ||
      normalized.includes("cardio") ||
      normalized.includes("run")
    ) {
      return "light";
    }
    if (normalized.includes("metabol") || normalized.includes("hiit")) {
      return "metabolic";
    }
    return "metabolic";
  },
  z.enum(["heavy", "light", "metabolic"]),
);

const WeightSchema = z.preprocess((value) => {
  if (typeof value === "number") return String(value);
  if (typeof value === "string" && value.trim()) return value.trim();
  return "Carga Media";
}, z.string());

const RepsSchema = z.union([z.string(), z.number()]).transform((value) => String(value));

// Schema for exercise in a routine block
export const ExerciseSchema = z.object({
  name: z.string(),
  reps: RepsSchema.describe('Rep range, e.g., "10-12"'),
  note: z.string().optional(),
  svg: z
    .enum([
      "pullup",
      "floor_press",
      "pushup_feet_elevated",
      "one_arm_row",
      "plank",
      "deadbug",
      "glute_bridge",
      "side_squat",
      "goblet_squat",
      "rdl",
      "calf_raise_bilateral",
      "face_pull",
      "bicep_curl",
      "tricep_extension",
      "shoulder_press",
      "leg_raise",
      "dumbbell",
      "barbell",
      "bodyweight",
    ])
    .optional(),
  // NEW: SVG Icon generated by AI
  svg_icon: z
    .string()
    .optional()
    .describe(
      "A simple, minimalist SVG string representing the exercise. <svg viewBox='0 0 24 24'>...</svg>",
    ),
  instructions: z.array(z.string()).optional(),
});
export type Exercise = z.infer<typeof ExerciseSchema>;

// Schema for a routine block
export const RoutineBlockSchema = z.object({
  id: z.coerce.number(),
  rest: z.coerce.number().min(0).default(60),
  exercises: z.array(ExerciseSchema).min(1),
});
export type RoutineBlock = z.infer<typeof RoutineBlockSchema>;

// Schema for a generated routine from Gemini
export const GeneratedRoutineSchema = z.object({
  title: z.string(),
  focus: z.string(),
  mode: ModeSchema,
  weight: WeightSchema,
  bg: z.string().default("bg-slate-900"),
  border: z.string().default("border-slate-800"),
  warmup: z
    .object({
      type: z.string().optional(),
      text: z.string(),
    })
    .optional(),
  cooldown: z
    .object({
      text: z.string(),
    })
    .optional(),
  blocks: z.array(RoutineBlockSchema).min(1),
});
export type GeneratedRoutine = z.infer<typeof GeneratedRoutineSchema>;

export const GeneratedProgramSchema = z.object({
  programName: z.string(),
  description: z.string(),
  days: z.array(GeneratedRoutineSchema),
});
export type GeneratedProgram = z.infer<typeof GeneratedProgramSchema>;

// Schema for nutrition log response - tolerant to AI quirks
const MealTypeSchemaForParse = z.preprocess(
  (value) => {
    if (typeof value !== "string") return "snack";
    const normalized = value.trim().toLowerCase();
    if (normalized.includes("breakfast") || normalized.includes("desayuno")) return "breakfast";
    if (
      normalized.includes("lunch") ||
      normalized.includes("almuerzo") ||
      normalized.includes("comida")
    )
      return "lunch";
    if (normalized.includes("dinner") || normalized.includes("cena")) return "dinner";
    return "snack";
  },
  z.enum(["breakfast", "lunch", "dinner", "snack"]),
);

export const MealTypeSchema = z.enum(["breakfast", "lunch", "dinner", "snack"]);

export const IngredientSchema = z.object({
  name: z.string(),
  amount: z.string().default("1 ración"),
  cal: z.coerce.number().min(0).default(0),
  p: z.coerce.number().min(0).default(0),
  c: z.coerce.number().min(0).default(0),
  f: z.coerce.number().min(0).default(0),
});

export const NutritionLogSchema = z.object({
  food: z.string().default("Comida").describe("Short, descriptive name of the meal"),
  calories: z.coerce.number().min(0).default(0).describe("Estimated kcal"),
  protein: z.coerce.number().min(0).default(0).describe("Estimated grams of protein"),
  carbs: z.coerce.number().min(0).default(0).describe("Estimated grams of carbs"),
  fats: z.coerce.number().min(0).default(0).describe("Estimated grams of fats"),
  mealType: MealTypeSchemaForParse,
  ingredients: z.array(IngredientSchema).optional().default([]),
});
